//! Static spell vocal → spell name groups.
//!
//! Update this table when BatMUD changes spell chant lines.

pub static VOCAL_SPELL_GROUPS: &[(&str, &[&str])] = &[
    (
        "In the Shadows cast down by the moon, a certain Elven lord he strolls among the common folk, cloaked and hidden from recognition. The dark streets of the Keep of Shadows, vehement Inns, dancing women appeasing patrons.. A vigorous gleam in his eye, a nod of knowledge and satisfaction; dreams slowly fulfilled as the notes of time pass, participating and watching the twists of life, Lord Shadowstring, the artful archwizard, grant us a fragment of chance.",
        &["Arches favour"],
    ),
    (
        "If you look behind a spider web, when it is covered with frost, You may see a tiny pixie, who perhaps is a little bit lost. That tiny pixie is full of spirit representing goodness and light, The embodiment of joy and laughter, of passion and sheer delight. In a world of pure imagination, and a mind full of magical dreams, An enchanted forest can exist, and so can a pixie it seems.",
        &["Kings feast"],
    ),
    (
        "Hear this charm, there in the dark, lurking fiends, devouring sharks. Lend me your ears, out in the mist. Where secrets lie, you cannot resist. The paths I traveled, the abyss I found, shall not be seen by any hound. Accept that, when these rhymes will end, only silence is your friend",
        &["Sounds of silence"],
    ),
    (
        "Green skins, white skins, black skins, purple skins. Big minds, small minds, dumb minds, silly minds. Can you see through yourself, I care not, for I can. I can see what you wear and what you bear, disguised or not, you",
        &["Jesters trivia"],
    ),
    (
        "Stand confused with lack of comprehension, pagan of mine for I know of the true belief, while death calls you, compel your soul to the true belief, for I offer you this redemption in the harmony of my true belief..",
        &["Achromatic eyes"],
    ),
    (
        "Dance my little blades, whip my enemies for I am the true fiend. Dance, for I am the source that tweaks the winds! Dance my blades, ravage at my command, for thou shall find sheaths in the abdomens of my foes!",
        &["Dancing blades"],
    ),
    (
        "To all the eyes around me, I wish to remain hidden, must I be seen when so far I have namelessly ridden. To all those who relentlessly me seek or hound, covet I nothing but mayhaps a trifling wound.",
        &["Clandestine thoughts"],
    ),
    (
        "..a few steps to earthen might, a few steps just go ahead me, but do I walk the right direction, is it here or there? Just a few steps, left or right. Spirits are what show the sight.",
        &["Venturers way"],
    ),
    (
        "Lost I am not but knowledge I seek for there, my friend, lies a true path for wisdom. With a clouded mind one can not think, but small fog may enhance a presence.",
        &["Vigilant melody"],
    ),
    (
        "Fo fu fe fum, Lord of the Winds, I know Thy ways, I know Thy names, I know Thy rest. Fo fu fe fum, show me paths or slay me now. Fo fe fi fum.",
        &["Pathfinder"],
    ),
    (
        "There is nothing you can do, when you realize with fright, that the Spider Queen is having you for dinner tonight... it",
        &["Sweet lullaby"],
    ),
    (
        "Feel your anger and strike with all your hatred. Use your aggressive feelings and let the hate flow through you. ",
        &["Aura of hate"],
    ),
    (
        "Salvage from the ice cold tomb, reveal the passage yonder womb. Float, not sink to darkness deep, for tomorrow we",
        &["Rapture of the deep"],
    ),
    (
        "III want to ROAR, III want to SLAM, III want to bash your ass! Hit the WALLS! Hit the WALLS! Go, go go I",
        &["Uncontrollable mosh"],
    ),
    (
        "Young bard he saw, a misjustice done, he took his instrument and pointed as a gun",
        &["Melody of the misadventurer"],
    ),
    (
        "Benedic, Faerwon, nos et haec tua dona quae de tua largitate sumus sumpturi.",
        &["Blessing of faerwon"],
    ),
    (
        "tastes and delights of nether star, served by thy host Draen-Dalar",
        &["Gluttony"],
    ),
    (
        "Harken to me and hear my plea, disease is what I call to thee",
        &["Pestilence"],
    ),
    (
        "Squirrel in the dirt, squirrel in the pool, squirrel don",
        &["Singing shepherd"],
    ),
    (
        "###### PORTTI HELVETTIIN AUKI, SAATANA JUMALAUTA ######",
        &["Demonic gate"],
    ),
    (
        "Thar! Rauko! Mor! Ris-Rim! Fuin-Heru! GOR! Gurthgwath!n",
        &["Noituloves deathlore"],
    ),
    (
        "War is TOTAL massacre, sport the war, war SUPPOORT!!!",
        &["War ensemble"],
    ),
    (
        "oli isa-sammakko, aiti-sammakko ja PIKKU-SAMMAKKO!!",
        &["Curse"],
    ),
    (
        "Grant this the caustic touch, to cleanse the world",
        &["Reaping of bile"],
    ),
    (
        "In the name of Faerwon, make this shield stronger",
        &["Divine enhancement"],
    ),
    (
        "ahne paskianen olen ma kun taikuutta nahda tahdon",
        &["See magic"],
    ),
    (
        "sulta taiat pois, mulle hyva mieli taikadaikaduu",
        &["Forget"],
    ),
    (
        "(May this become the blood of the Spider queen)",
        &["Venom blade"],
    ),
    (
        "(arachnid infernalicus arachnoidus demonicus)",
        &["Spider demon conjuration"],
    ),
    (
        "It is time for the harvest of bone and blood",
        &["Call scythe"],
    ),
    (
        "Now that two decades gone by and I know that",
        &["Soothing sounds"],
    ),
    (
        "Once there were two knights and maidens They",
        &["Melodical embracement"],
    ),
    (
        "What child is this, who laid to rest on Mary",
        &["Campfire tune"],
    ),
    (
        "Azzarakk, take this sacrifice I offer thee!",
        &["Black hole"],
    ),
    (
        "Let this strike true, to burn from within",
        &["Immolate scythe"],
    ),
    (
        "moon fiksu, soot tyhma  - opi tasta taika",
        &["Spellteaching"],
    ),
    (
        "(infernalicus domus arachnid rex magnos)",
        &["Spider demon mass sacrifice"],
    ),
    (
        "Grant me the power, the fire from within",
        &["Glory of destruction"],
    ),
    ("That which I ask, I shall return tenfold", &["Call armour"]),
    ("juustoa ja pullaa, sita mun maha halajaa", &["Create food"]),
    ("(infernalicus claravonticus arachnidos)", &["Spider gaze"]),
    ("Vita non est vivere sed valere vita est", &["Cantrip"]),
    ("hooooooooooowwwwwwwwwwwlllllllllllllll", &["Drying wind"]),
    ("yugfzhrrr suuck suuuuuck suuuuuuuuuuck", &["Energy drain"]),
    ("(ddt ddt ddt is good for you and me!)", &["Poison cloud"]),
    (
        "Ala itkeä iletys, parkua paha kuvatus",
        &["Cleanse heathen"],
    ),
    (
        "Grant your worshipper your protection",
        &["Shield of faith"],
    ),
    (
        "sulphiraidzik hydrochloodriz gidz zuf",
        &["Corrosion shield"],
    ),
    ("(infernalicus conjuratis arachnidos)", &["Spider servant"]),
    ("(infernalicus intellegus arachnidos)", &["Spider eye"]),
    ("(insignificus et gargantum alternos)", &["Transfor golem"]),
    (
        "bii thee dzname uv tii blaaaz drazon",
        &["Resist disintegrate"],
    ),
    ("niihek atierapip aj niiramaan aaffaj", &["Psionic shield"]),
    ("Blaarh ARGHAGHAHAHA URAAAH BELARGH!", &["Reanimation"]),
    ("I need someone to watch this for me", &["Summon squire"]),
    (
        "spirits of nature, show me the way!",
        &["Wilderness location"],
    ),
    ("taxonimus zoologica whaddahellizzat", &["Detect race"]),
    (
        "(infernalicus thanatos arachnidos)",
        &["Spider demon banishment"],
    ),
    ("That I have set free, return to me", &["Shattered feast"]),
    ("insignificus et gargantum alternos", &["Transform golem"]),
    ("whoosy banzziii pal eeeiizz dooneb", &["Dispel good"]),
    ("(Khizanth Arachnidus Diametricus)", &["Spider touch"]),
    (
        "(Khizanth Arachnidus Satisfusmus)",
        &["Prayer to the spider queen"],
    ),
    (
        "(infernalicus domus arachnid rex)",
        &["Spider demon control"],
    ),
    (
        "(infernalicus nexus arachnid rex)",
        &["Spider demon channeling"],
    ),
    ("Judicandee iocus merciaa Tarmalen", &["Guardian angel"]),
    ("Stand back divinity Hael-Cholaer", &["Banish angels"]),
    ("aamad ato naav aanarub atyak ala", &["Psychic purge"]),
    ("ghht mar nak grttzt gnatlnamauch", &["Vacuum globe"]),
    ("gtzt mar nak grttzt gnatlnamauch", &["Magic eruption"]),
    ("krkx mar nak grttzt gnatlnamauch", &["Killing cloud"]),
    ("(Khizanth Arachnidus Iracundus)", &["Spider wrath"]),
    (
        "Hrrrrrrrrhhrrr rrrhhhHHrrrr rrr",
        &["Touch of glacial winds"],
    ),
    ("cah mar nak grttzt gnatlnamauch", &["Hailstorm"]),
    ("diir mieelis sxil miarr mieelin", &["Mindseize"]),
    ("fah mar nak grttzt gnatlnamauch", &["Lava storm"]),
    ("fzz mar nak grttzt gnatlnamauch", &["Acid storm"]),
    ("omm mar nak grttzt gnatlnamauch", &["Psychic storm"]),
    ("sayora maradan edio cor tempora", &["Sands of time"]),
    ("scientia et experientia sagitta", &["Bolt of knowledge"]),
    ("zot mar nak grttzt gnatlnamauch", &["Lightning storm"]),
    ("(Khirsah Khazanth Arachinidus)", &["Spider gate"]),
    ("Ab sinestris, mortum demitteri", &["Last rites"]),
    ("Forces of Chaos, heed my call!", &["Aura of chaos"]),
    ("grhagrhagrhagrah gra gra Hyaa!", &["Channelburn"]),
    ("ja nyt kenka kepposasti nousee", &["Field of light"]),
    ("trpp dda prtolala offf pwerrrr", &["Rune of warding"]),
    ("(Khizanth Arachnidus Vitalis)", &["Hunger of the spider"]),
    ("Akronym Htouy, Hokrune Arafax", &["Youth"]),
    ("Corporem Connecticut Corporee", &["Life link"]),
    ("Grrrnaakk Azt-Glassyallobolas", &["Fury of nature"]),
    ("I choose you, umm, whoever...", &["Ghost companion"]),
    ("Naturallis Judicandus Imellys", &["Natural renewal"]),
    ("Unitus vitae nexus communium!", &["Healbound harmony"]),
    ("all for one, gather around me", &["Psionic phalanx"]),
    ("holitorius veneficium aspergo", &["Herbal poison spray"]),
    ("holitorius veneficium curatio", &["Herbal remove poison"]),
    ("holitorius veneficium sagitta", &["Herbal poison blast"]),
    (
        "nyiaha llaimay exchekes ployp",
        &["Shield of detoxification"],
    ),
    ("peilikuvia ja lasinsirpaleita", &["Mirror image"]),
    ("redoc mirahk rof airgnas erom", &["Sleeping parasite"]),
    ("serve me well, faithful steed", &["Noble mount"]),
    ("toughen da mind reeez un biis", &["Psychic sanctuary"]),
    ("I beseech thy wisdom my lord", &["Unholy matrimony"]),
    ("Khizanth Arachnidus Walkitus", &["Spider walk"]),
    ("bloozdy etherum errazam zunk", &["Create air armour"]),
    (
        "blueeeeeeeeeee****saka??am!a",
        &["Protect armour", "Protect item", "Protect weapon"],
    ),
    ("heal soil from dirt you grow", &["Curse nature"]),
    ("homines, dum docent, discunt", &["Beacon of enlightenment"]),
    ("hypin pompin luokses juoksen", &["Relocate"]),
    ("kablaaaammmmm bliitz zundfer", &["Energy channeling"]),
    ("nihenuak assaam no nek orrek", &["Transmute self"]),
    ("tooassim nenovehanroh uukkuk", &["Glance of predator"]),
    ("voi hellapoliisin kevatnuija", &["Suppress magic"]),
    ("whaat timaaa of daaa maaanth", &["Lunar inspiration"]),
    ("(Khirsah Zokant Arachnidus)", &["Spider demon inquiry"]),
    ("come to me, faithful steed!", &["Summon mount"]),
    (
        "cryptozoologicus munimentum",
        &["Cryptozoological protection"],
    ),
    ("daaa timaaa of daaa maaanth", &["Moon sense"]),
    ("fooharribah inaminos cantor", &["Armour of aether"]),
    ("fooohh haaahhh booooloooooh", &["Aura detection"]),
    ("ghht zur semen gnatlnamauch", &["Vacuum ball"]),
    ("gtzt zur semen gnatlnamauch", &["Magic wave"]),
    ("huumeet miehen tiella pitaa", &["Hallucination"]),
    (
        "kinemortologicus munimentum",
        &["Kinemortological protection"],
    ),
    ("krkx zur semen gnatlnamauch", &["Poison spray"]),
    ("vaka tosi vanha vainamoinen", &["Area entropy"]),
    ("..... .... ... ..  .    .!", &["Invisibility"]),
    ("Faerwon, grant your favor!", &["Bless armament"]),
    ("cah zur semen gnatlnamauch", &["Cone of cold"]),
    ("fah zur semen gnatlnamauch", &["Meteor swarm"]),
    ("fzz zur semen gnatlnamauch", &["Acid rain"]),
    ("incantar combustis aggriva", &["Spontaneous combustion"]),
    ("judicandus puorgo mangenic", &["Major party heal"]),
    ("omm zur semen gnatlnamauch", &["Psychic shout"]),
    ("zot zur semen gnatlnamauch", &["Chain lightning"]),
    ("Beware the big bad troll!", &["Elemental soul ward"]),
    ("aaaaaaaaattchhhoooooooooo", &["Sneezing powder"]),
    ("biecnan ambihtere hercyme", &["Beckon rift entity"]),
    ("cuman agotenes ond cweman", &["Summon rift entity"]),
    ("diffingo genus munimentum", &["Attune racial protection"]),
    ("jammpa humppa ryydy mopsi", &["Flip"]),
    ("judicandus eurto mangenic", &["True party heal"]),
    ("nullum driiiks umbah mana", &["Mana shield"]),
    ("saldia nen yru gerue wefe", &["Blight of the shunned"]),
    ("tady urcite bydlet nechci", &["Control marsh"]),
    ("xafe xyyqh xckgandhuzqarr", &["Teleport with error"]),
    ("$$$$$$$$$$$$$$$$$$$$$$$$", &["Money is power"]),
    ("Aelores barrimus maximus", &["Conjure element"]),
    ("Aelores barrimus minimus", &["Conjure lesser element"]),
    ("How to measure a planet?", &["Recall animal soul"]),
    ("The sharper, the sweeter", &["Blood seeker"]),
    ("Ziiiiiiiiit Ziiit Ziiiit", &["Electric field"]),
    ("aalltyyuii regonza zirii", &["Clairvoyance"]),
    ("bring your might to bear", &["Retool armament"]),
    ("easy there, whoa, steady", &["Heal mount"]),
    ("hot hot not zeis daimons", &["Heat reduction"]),
    ("incantar amperea aggriva", &["Grounding point"]),
    ("incantar enfeugo aggriva", &["Energy vortex"]),
    ("judicandus puorgo ignius", &["Minor party heal"]),
    ("misery ior noctar report", &["Detect misery"]),
    ("shamarubu incixtes delfo", &["Repulsor aura"]),
    ("skaki barictos yetz fiil", &["Frost insulation"]),
    ("thanatia ariobal lusengo", &["Here and after"]),
    ("thoiiiiiisss huuuiahashn", &["Force shield"]),
    ("(sakenoivasta voimasta)", &["Haste"]),
    ("Esrpriestitst hjajjossa", &["Shield of transcendence"]),
    ("Give my creation life!!", &["Animate golem"]),
    ("Jeeeeeeeeeeeesuuuuuuuus", &["Water walking"]),
    ("Rzzakkaa Khaar Gaggnath", &["Summon dire boar"]),
    ("Siwa on selvaa saastoa.", &["Restore"]),
    ("be whole, gentle spirit", &["Noble animal spirit"]),
    ("doowesh maiket fyoleue?", &["Spell empathy"]),
    ("flzeeeziiiiying nyyyaaa", &["Go"]),
    ("null, nill, noll, nutin", &["Neutralize field"]),
    ("phalantia elitae mortee", &["Soul guardian"]),
    ("ragus on etsat mumixam!", &["Unstable mutation"]),
    ("rhuuuumm angotz amprltz", &["Cause serious wounds"]),
    ("rhuuuumm angotz klekltz", &["Cause critical wounds"]),
    ("thanatia zuna levetalis", &["Gangrenous coils"]),
    ("transformaticus minimus", &["Feather weight"]),
    ("vokinsalak elfirtluassa", &["Raise dead"]),
    ("well, what have we here", &["Arms lore"]),
    ("xafe ayz xckgandhuzqarr", &["Teleport without error"]),
    ("(tamakan natelo assim)", &["All-seeing eye"]),
    ("Creo Herbamus Satisfus", &["Satiate person"]),
    ("FDSSSfssspleeeh... feh", &["Remove curse"]),
    ("Kavereita kaikki tynni", &["Vampiric charm"]),
    ("eki eki eki equifaxeki", &["Credit check"]),
    ("etheria aquariq nihilz", &["Goto ship"]),
    ("forscieppan ambihtmecg", &["Transform rift entity"]),
    ("grinurb sdan imflagrum", &["Channelspray"]),
    ("hfizz hfizz nglurglptz", &["Acid shield"]),
    ("jumpiiz laika wabbitzz", &["Quicksilver"]),
    ("koko mudi kuntoon, hep", &["Heal all"]),
    ("maergal ania phalantia", &["Phantasmal reflection"]),
    ("nilaehz temnahecne neg", &["Curse of tarmalen"]),
    ("niotalucaje erutamerp!", &["Holding pattern"]),
    ("okta atsavi osnile hup", &["Travel"]),
    ("pqwioeu aslkdjfh zxmcb", &["Planar gate"]),
    ("thanatia sadur dalaris", &["Necrotic bane"]),
    ("vaka vanha vainamoinen", &["Entropy"]),
    ("Ourglazz Schmourglazz", &["Resist entropy"]),
    ("aatevehal inok arepyt", &["Banish mount"]),
    ("bufo mortui maledicum", &["Summon slaads"]),
    ("buuuummbzdiiiiiibummm", &["Mobile cannon"]),
    ("grandis magicus draco", &["Greater magic mount"]),
    ("hhhnnnnnrrrrraaahhh!!", &["Absorption aura", "Energy aura"]),
    ("huppa huppa tiki tiki", &["Flame shield"]),
    ("imprickening zang gah", &["Imprisonment"]),
    ("join, meld, communion", &["Join soul"]),
    ("kewa dan dol rae hout", &["Degenerate person"]),
    ("nbarrimon zfettix roi", &["Frost shield"]),
    ("prtolala offf pwerrrr", &["Dimension door"]),
    ("silent moon sour mood", &["Despair"]),
    ("slash, cut, severance", &["Separate soul"]),
    ("teniara lais alluvana", &["Nocturnal charm"]),
    ("tic tac rise brethren", &["Wrath beyond grave"]),
    ("transformo vermiculus", &["Bookworm"]),
    ("zoologicus munimentum", &["Zoological protection"]),
    ("Annatheer graaweizta", &["Mind development"]),
    ("Nogg Saalah Hzzarrkk", &["Summon beasts"]),
    ("Shiaha azgra zgra za", &["Defile animal"]),
    ("Zanctum Zanctus Aqua", &["Bless vial"]),
    ("amplifico veneficium", &["Field of poison"]),
    ("annihilar hzzz golum", &["Detect alignment"]),
    ("burglum bufo mutatio", &["Curse of slaads"]),
    ("elonaria inaiar bufo", &["Evoke toad"]),
    ("gebreadian ambihtere", &["Regenerate rift entity"]),
    ("greeeenie fiiingerie", &["Create herb"]),
    ("havia kauhistus pois", &["Banish"]),
    ("judicandus pafzarmus", &["Major heal"]),
    ("judicandus pzarcumus", &["Minor heal"]),
    ("morri nam pantoloosa", &["Toxic dilution"]),
    ("nostaaaanndiz noszum", &["Iron will"]),
    ("roope ankka rulettaa", &["Create money"]),
    ("ruotsalainen ensiapu", &["Half harm"]),
    ("sanguinum lnarae est", &["Curse of lycanthropy"]),
    ("shatter aquar sphorq", &["Disrupt magic"]),
    ("symur nahder relegus", &["Magica pandemonica"]),
    ("tevenyt tietree akta", &["Aura of irreverence"]),
    ("Avee Alee adudaaa..", &["Holy way"]),
    ("corpus novus foobar", &["New body"]),
    ("fah mar nak prztrzz", &["Searing fervor"]),
    ("ghht mar nak grttzt", &["Blast vacuum"]),
    ("gtzt mar nak grttzt", &["Golden arrow"]),
    ("harnaxan temnahecne", &["Unpain"]),
    ("judicandus littleee", &["Heal self"]),
    ("judicandus mangenic", &["Cure critical wounds"]),
    ("judicandus mercuree", &["Cure light wounds"]),
    ("judicandus saugaiii", &["Remove poison"]),
    ("judicandus zapracus", &["True heal"]),
    ("krkx mar nak grttzt", &["Summon carnal spores"]),
    ("lecaps meeb nonnock", &["Channelray"]),
    ("lkzaz zueei enz orn", &["Remove scar"]),
    ("naxanhar hecnatemne", &["Soul hold"]),
    ("servo nos ex cambia", &["Lunacy shield"]),
    ("shar ryo den...Haa!", &["Channelball"]),
    ("vole love velo levo", &["Word of recall"]),
    ("$%&@ #*%@*@# $&*@#", &["See invisible"]),
    ("Agnah az argaahath", &["Eyes of nature"]),
    ("Renew our strength", &["Laying on hands"]),
    ("annihilar thanatia", &["Detect death"]),
    ("aqua anitrap eselb", &["Curse ship"]),
    ("blese partina aqua", &["Bless ship"]),
    ("cah mar nak grttzt", &["Cold ray"]),
    ("condiiit riimaynii", &["Aegis"]),
    ("diiiiuuunz aaanziz", &["Displacement"]),
    ("enfuego delvivendo", &["Drain enemy"]),
    ("enfuegome delterra", &["Drain room"]),
    ("fah mar nak grttzt", &["Lava blast"]),
    ("fingerrrr ovuuulah", &["Mould ring"]),
    ("fzz mar nak grttzt", &["Acid blast"]),
    ("fzz zur tumblzegar", &["Lock biter"]),
    ("ghht mar nak semen", &["Strangulation"]),
    ("gloria malum mundi", &["Glorification of sin"]),
    ("grrreee allblakkee", &["Dim"]),
    ("gtzt mar nak semen", &["Summon greater spores"]),
    ("histria aqua fevia", &["Fire of the saints"]),
    ("holitorius curatio", &["Herbal healing"]),
    ("isar avatap patyan", &["Enhance vision"]),
    ("krkx mar nak semen", &["Power blast"]),
    ("krkx zur interroga", &["Poison scan"]),
    ("mi casa es su casa", &["Animal soul link"]),
    ("nidgenga ambihtere", &["Dismiss rift entity"]),
    ("nilaehz temnahecne", &["Regeneration"]),
    ("puujalka jumalauta", &["Harm"]),
    ("shalambala shoashu", &["Golem heal"]),
    ("upo huurre helkama", &["Preserve corpse"]),
    ("wheeeaaaaaa oooooo", &["Field of fear"]),
    ("withing thang walz", &["Shelter"]),
    ("xulu tango charlie", &["Force dome"]),
    ("zot mar nak grttzt", &["Electrocution"]),
    ("ztonez des deckers", &["Force absorption"]),
    (" -¤- Zanctus -¤- ", &["Guardian"]),
    ("Donations welcome", &["Musicians alm"]),
    ("Impuqueto es Bien", &["Lessen poison"]),
    ("Ouch ouch ow oww!", &["Mana barrier"]),
    ("Zmasching Pupkins", &["Mellon collie"]),
    ("abitan campwaepen", &["Consume weapon"]),
    ("aqualin shieferus", &["Ship armour"]),
    ("asaelan ambihtere", &["Bind rift entity"]),
    ("bredan forswelgan", &["Absorbing meld"]),
    ("cah mar nak semen", &["Icebolt"]),
    ("eyem en da munnee", &["Cash flow"]),
    ("fah mar nak semen", &["Meteor blast"]),
    ("fah relep krlnpth", &["Immolate"]),
    ("fzz mar nak semen", &["Acid ray"]),
    ("ghht mar zrrprghh", &["Air shield"]),
    ("gimme gimme gimme", &["Ghost link"]),
    ("gtzt zur illumina", &["Mana beacon"]),
    ("judicandus ignius", &["Cure serious wounds"]),
    ("krkx murk arrsunt", &["Noxious fumes"]),
    ("lentavia lauseita", &["Floating letters"]),
    ("mega visa huijari", &["Identify"]),
    ("nilaehz arzocupne", &["Blessing of tarmalen"]),
    ("nyt muuten napsuu", &["True harm"]),
    ("omm mar nak semen", &["Mind disruption"]),
    ("parvus munimentum", &["Minor protection"]),
    ("removezzzzzarmour", &["Dispel magical protection"]),
    ("sanatagras teceah", &["Steed of tzarakk"]),
    ("taikoja ma inhoan", &["Anti magic field"]),
    ("tossikid jullitta", &["Touch of madness"]),
    ("tuo fo wen stanhc", &["Resurrect"]),
    ("zot mar nak semen", &["Forked lightning"]),
    ("zot sur gaussimen", &["Magnetic levitation"]),
    ("astellan geweald", &["Establish entity control"]),
    ("come, come, come", &["Resurrect soul"]),
    ("demoni on pomoni", &["Infravision"]),
    ("enfuegamos delyo", &["Replenish party"]),
    ("englobo globo mc", &["Aura of wind"]),
    ("genus munimentum", &["Racial protection"]),
    ("hena xai anissai", &["Forbidden wards"]),
    ("idel claeppetung", &["Rift pulse"]),
    ("invictus Kofgaad", &["Blessing of kofgaad"]),
    ("itsy bitsy chill", &["Ghost chill"]),
    ("kakakaaa  tsooon", &["Mental watch"]),
    ("kerubi on pomoni", &["Ghost vision"]),
    ("lano i tanr etni", &["Soul chorus"]),
    ("likz az zurgeeon", &["Sex change"]),
    ("rex car bus xzar", &["Floating disc"]),
    ("rolaqua refintis", &["Holy armada"]),
    ("sanctus Exzordus", &["Protection from evil"]),
    ("the light within", &["Holy glow"]),
    ("tosi pieni neula", &["Cause light wounds"]),
    ("vaxtextraktdryck", &["Mental glance"]),
    ("Battlestations!", &["Ghost guidance"]),
    ("Eeneil okayssiv", &["Detect vial"]),
    ("Kindred spirits", &["Conjure animal soul"]),
    ("You say you don", &["Strength in unity"]),
    ("aa tuuti lullaa", &["Restful sleep"]),
    ("cah zur bonccus", &["Create frost weapon"]),
    ("cennan swelgend", &["Create rift vortex"]),
    ("enfuego delcosa", &["Drain item"]),
    ("enfuego delmigo", &["Drain ally"]),
    ("etati elem ekam", &["Levitation"]),
    ("freudemas egoid", &["Cure player"]),
    ("grrreee gelowwa", &["Glow"]),
    ("imppy floooogah", &["Summon homonculus"]),
    ("jimmiii fixiiii", &["Patch item"]),
    ("ranae paludibus", &["Unleash bogs"]),
    ("rikki ja poikki", &["Destroy weapon"]),
    ("sanctus angeliq", &["Soul shield"]),
    ("se on sarki nyt", &["Destroy armour"]),
    ("sezdaron montir", &["Good berry"]),
    ("zicks laai qluu", &["Resist dispel"]),
    ("(Polo Polomii)", &["Flame fists"]),
    ("(Tiger Power!)", &["Tiger mask"]),
    ("Animal Aspects", &["Animal aspect"]),
    ("BBBBOOOOOO!!!!", &["Terror"]),
    ("Fly my pretty!", &["Kinematic projection"]),
    ("Rez vas na ful", &["Nightfall"]),
    ("Sanctum circum", &["Holy bolt"]),
    ("Sanctum disqum", &["Dispel undead"]),
    ("dsaflk aslfoir", &["Blade of fire"]),
    ("ghht zur semen", &["Chaos bolt"]),
    ("gtzt zur semen", &["Levin bolt"]),
    ("huku mopo huku", &["Rain"]),
    ("jack-o-lantern", &["Ghost light"]),
    ("jakki makupala", &["There not there"]),
    ("kallora kassam", &["Shift blade"]),
    ("krkx zur semen", &["Venom strike"]),
    ("meke tul magic", &["Magic dispersion"]),
    ("nyuk nyuk nyuk", &["Uncontrollable hideous laughter"]),
    ("ogyawaelbirroh", &["See the light"]),
    ("qor monoliftus", &["Ether boundary"]),
    ("rise Rise RISE", &["Floating"]),
    ("swicung asucan", &["Rift scramble"]),
    ("tauko paikalla", &["Appease ghost"]),
    ("thanatia sinna", &["Mark of death"]),
    ("tora tora tora", &["Psychic crush"]),
    ("viiltaja jaska", &["Make scar"]),
    ("vorek ky taree", &["Paralyze"]),
    ("ziiiuuuuns wiz", &["Blurred image"]),
    ("zoot zoot zoot", &["Enhanced vitality"]),
    ("Gawd DAMN IT!", &["Damn armament"]),
    ("Sanctus inxze", &["Holy hand"]),
    ("azkura colere", &["Prismatic burst"]),
    ("cah zur semen", &["Darkfire"]),
    ("enfuego delyo", &["Replenish ally"]),
    ("fah zur semen", &["Fire blast"]),
    ("fzz zur semen", &["Acid arrow"]),
    ("gant sit niie", &["Telekinetic whirlwind"]),
    ("ghht zur fehh", &["Vacuumbolt"]),
    ("ghht zur sanc", &["Suffocation"]),
    ("gtzt zur fehh", &["Magic missile"]),
    ("gtzt zur sanc", &["Summon lesser spores"]),
    ("inficio vivus", &["Living poison"]),
    ("kakkosnelonen", &["Ghost sword"]),
    ("krkx zur fehh", &["Thorn spray"]),
    ("krkx zur sanc", &["Poison blast"]),
    ("magicus equus", &["Magic mount"]),
    ("memono locati", &["Mind store"]),
    ("noccon duumof", &["Granitize"]),
    ("noccon uurthg", &["Disease"]),
    ("omm zur semen", &["Psi blast"]),
    ("phylli phylli", &["Prepare flask"]),
    ("rtsstr dummof", &["Strengthen"]),
    ("rtsstr uurthg", &["Curse of ogre"]),
    ("sanctus . o O", &["Heavenly protection"]),
    ("scutum mortia", &["Bulwark of death"]),
    ("siwwis duumof", &["Enwize"]),
    ("siwwis uurthg", &["Amnesia"]),
    ("xeddex duumof", &["Speed"]),
    ("xeddex uurthg", &["Wither"]),
    ("zot zur semen", &["Blast lightning"]),
    ("AeaH*h***Gdg", &["Con fioco"]),
    ("Good is dumb", &["Protection from good"]),
    ("I HATE MAGIC", &["Mana drain"]),
    ("PAF PAF PAF!", &["Harm body"]),
    ("aire sanguim", &["Crimson mist"]),
    ("alak seicsip", &["Teeming waters"]),
    ("cah zur fehh", &["Chill touch"]),
    ("cah zur sanc", &["Flaming ice"]),
    ("creo herbula", &["Greater create herb"]),
    ("fah zur fehh", &["Flame arrow"]),
    ("fah zur sanc", &["Firebolt"]),
    ("fzz zur fehh", &["Disruption"]),
    ("fzz zur sanc", &["Acid wind"]),
    ("gimme urhits", &["Life leech"]),
    ("henget uusix", &["Reincarnation"]),
    ("nitin duumof", &["Intelligize"]),
    ("nitin uurthg", &["Feeblemind"]),
    ("noxim delusa", &["Paranoia"]),
    ("omm zur fehh", &["Mind blast"]),
    ("omm zur sanc", &["Psibolt"]),
    ("zot zur fehh", &["Shocking grasp"]),
    ("zot zur sanc", &["Lightning bolt"]),
    ("Bewareeeee!", &["Enhanced awareness"]),
    ("cwician ysl", &["Spark birth"]),
    ("fzeziiignya", &["Escape velocity"]),
    ("habbi urblk", &["Call pigeon"]),
    ("lkrp ajuvah", &["Mesmeric threshold"]),
    ("mad rad dar", &["Wizard eye"]),
    ("mumbo jumbo", &["Deaths door"]),
    ("poskid ujsi", &["Psychic shackles"]),
    ("tokku rassa", &["Drunken stupor"]),
    ("uniara bufo", &["Resist curse"]),
    ("uoogachucka", &["Dimensional vacuum"]),
    ("xafe uurthq", &["Phaze shift"]),
    ("yugzhrr paf", &["Aneurysm"]),
    (" ¤Lassum¤ ", &["Wrath of las"]),
    ("(saugaiii)", &["Poison"]),
    ("Satan down", &["Banish demons"]),
    ("aiwuhfiueh", &["Slingshot vortex"]),
    ("cennan gin", &["Create rift"]),
    ("gwanna fio", &["Cleanse weapon"]),
    ("idel laece", &["Dimensional leech"]),
    ("noccon mof", &["Aura of power"]),
    ("protect me", &["Ghost armour"]),
    ("rtsstr mof", &["Giant strength"]),
    ("sahanpurua", &["Disintegrate"]),
    ("siwwis mof", &["Awareness"]),
    ("tonnikalaa", &["Heavy weight"]),
    ("vas na ful", &["Greater darkness"]),
    ("xeddex mof", &["Agility accelerator"]),
    ("JJAAAWWWG", &["Mass summon"]),
    ("Sancte Di", &["Holy lance"]),
    ("bat-o-mat", &["Remote banking"]),
    ("karapuche", &["Destroy water"]),
    ("nitin mof", &["Artificial intelligence"]),
    ("FRONOX!!", &["Word of oblivion"]),
    ("Myh myh!", &["Lift of load"]),
    ("Sherpha!", &["Word of destruction"]),
    ("aflitruz", &["Stoneskin"]),
    ("dIsCHoRD", &["Noituloves dischord"]),
    ("gwwaaajj", &["Summon"]),
    ("klainmox", &["Shadow armour"]),
    ("murraugh", &["Bearskin"]),
    ("myarhees", &["Airsteel"]),
    ("nsiiznau", &["Shield of protection"]),
    ("! (*) !", &["Blessed warmth"]),
    ("(Haii!)", &["Shadow leap", "Tiger claw"]),
    ("Bastage", &["Bastardly balm"]),
    ("Exzorde", &["Saintly touch"]),
    ("cuppajo", &["Hangover cure"]),
    ("dephtua", &["Word of genocide"]),
    ("tandala", &["Zealotry"]),
    ("torrfra", &["Word of spite"]),
    ("tsaibaa", &["Channelbolt"]),
    ("vas ful", &["Greater light"]),
    ("yugzhrr", &["Hemorrhage"]),
    ("zeriqum", &["Celestial haven"]),
    ("zug zug", &["Create dimensional gem"]),
    ("** /|/", &["Summon storm"]),
    ("@% ()@", &["Gust of wind"]),
    ("dymofo", &["Word of apocalypse"]),
    ("hraugh", &["Word of blasting"]),
    ("khozak", &["Word of attrition"]),
    ("na ful", &["Darkness"]),
    ("riljya", &["Personal force field"]),
    ("!( !!", &["Star light"]),
    ("!( *)", &["Earth blood"]),
    ("\"\" !#", &["Vine mantle"]),
    ("\") !#", &["Transfer mana"]),
    ("Paxus", &["Unstun"]),
    ("haven", &["Monster lore"]),
    ("niinr", &["Word of slaughter"]),
    ("!* %", &["Replenish energy"]),
    ("!* *", &["Runic heal"]),
    ("\"# ^", &["Wither flesh"]),
    ("# !#", &["Create mud"]),
    ("# !(", &["Charge staff"]),
    ("# !^", &["Detect poison"]),
    ("$ !^", &["Drain pool"]),
    ("% !(", &["Earth skin"]),
    ("% !^", &["Earth power"]),
    ("@& ^", &["Natural transformation"]),
    ("Rev ", &["Holy wind"]),
    ("^ !)", &["Flex shield"]),
    ("& ^", &["Gem fire", "Hoar frost"]),
    ("ful", &["Light"]),
    (
        "ner",
        &[
            "Awake enthralled",
            "Call forth enthralled",
            "Corrupt ground",
            "Crippling frenzy",
            "End enthrallment",
            "Enthralling parasite",
            "Evaluate host",
            "Foul drought",
            "Harvest vitae",
            "Legacy of enthralled",
            "Mind siphon",
            "Nourish enthralled",
            "Parasitic swarm",
            "Putrid blood",
            "Reap potentia",
            "Suppressing misery",
        ],
    ),
    ("ohm", &["Lightning shield"]),
    ("qxx", &["Resist temptation"]),
    ("srR", &["Identify relic"]),
    ("!(", &["Shapechange"]),
    ("!?", &["Inquiry to ahm"]),
    ("Ez", &["Dispel evil"]),
    ("ex", &["Flames of righteousness"]),
    ("it", &["Protect mount"]),
    ("%", &["Earthquake"]),
    ("0", &["Catchy singalong"]),
    ("I", &["Blessing of intoxication", "Spirit drain"]),
    ("b", &["Instant fermentation"]),
    ("h", &["Item dispersion shield"]),
];
