# Generated by agentic-config.
# Run from the project root: .\.agentic-config\install.ps1
param(
  [switch]$DryRun,
  [switch]$Force,
  [switch]$SkipPi,
  [switch]$SkipSkills,
  [switch]$SkipEnvCheck,
  [switch]$Strict
)

$ErrorActionPreference = "Stop"
$ScriptDir = $PSScriptRoot
$ProjectRoot = Split-Path -Parent $ScriptDir
$PlanPath = Join-Path $ScriptDir "install-plan.json"
$MinNodeMajor = 24

# --- Install type detection (before any overwrites) ---
$InstallType = ""
function Test-PriorAdcInHead {
  $GitHead = git rev-parse HEAD 2>$null
  if ($LASTEXITCODE -ne 0) { return $false }
  git show HEAD:.agentic-config/manifest.json 2>$null | Out-Null
  if ($LASTEXITCODE -eq 0) { return $true }
  $paths = git ls-tree -r --name-only HEAD 2>$null
  return [bool]($paths | Where-Object { $_ -like '.agentic-config/*' } | Select-Object -First 1)
}
$GitHead = git rev-parse HEAD 2>$null
if ($LASTEXITCODE -eq 0) {
  if (Test-PriorAdcInHead) {
    $InstallType = "update"
  } else {
    $InstallType = "integration"
  }
} else {
  $InstallType = "greenfield"
}

$ToolHelp = @{
  jq   = @("Docs:    https://jqlang.org/download/", "Install: winget install jqlang.jq", "         # or: choco install jq")
  node = @("Docs:    https://nodejs.org/", "Install: winget install OpenJS.NodeJS.LTS", "         # or: https://nodejs.org/en/download/")
  npx  = @("Docs:    https://docs.npmjs.com/cli/v10/commands/npx", "Note:    npx ships with Node.js - install Node.js first.")
  pi   = @("Docs:    https://pi.dev/docs/latest/usage#cli-reference", "Install: npm install -g @earendil-works/pi-coding-agent")
  curl = @("Docs:    https://curl.se/download.html", "Install: winget install cURL.cURL")
  wget = @("Docs:    https://www.gnu.org/software/wget/", "Install: winget install JernejSimoncic.Wget")
  git  = @("Docs:    https://git-scm.com/downloads", "Install: winget install Git.Git")
  python3 = @(
    "Docs:    https://www.python.org/downloads/"
    "Install: winget install Python.Python.3.12"
    "Note:    Only required when an install step invokes python3 directly; Graphify uses uv-managed Python."
  )
  uv = @(
    "Docs:    https://docs.astral.sh/uv/getting-started/installation/"
    "Install: powershell -ExecutionPolicy Bypass -c `"irm https://astral.sh/uv/install.ps1 | iex`""
    "Note:    Graphify uses ``uv tool install graphifyy[mcp]``; Headroom uses ``uv tool install 'headroom-ai[proxy,mcp]'``."
  )
  graphify = @(
    "Docs:    https://github.com/safishamsi/graphify"
    "Note:    Installed by the graphify-tool-install step via ``uv tool install graphifyy[mcp]``."
    "Install: add %USERPROFILE%\.local\bin to PATH (uv tool install places the CLI there)."
  )
  headroom = @(
    "Docs:    https://github.com/headroomlabs-ai/headroom"
    "Note:    Installed by the headroom-tool-install step via ``uv tool install 'headroom-ai[proxy,mcp]'``."
    "Note:    PyPI headroom-ai has no Windows wheels; install.ps1 also passes --no-binary-package ast-grep-cli (Defender quarantine on prebuilt sg.exe)."
    "Note:    Native Windows needs Rust (cargo) and MSVC C++ Build Tools (link.exe), or WSL."
    "Install: add %USERPROFILE%\.local\bin to PATH (uv tool install places the CLI there)."
  )
  cargo = @(
    "Docs:    https://rustup.rs/"
    "Install: winget install Rustlang.Rustup"
    "         # or: https://rustup.rs/ (then restart the shell so cargo is on PATH)"
    "Note:    Required on native Windows when headroom-tool-install is in the plan (PyPI has no Windows wheels)."
  )
  msvc = @(
    "Docs:    https://visualstudio.microsoft.com/visual-cpp-build-tools/"
    "Install: Visual Studio Build Tools with Desktop development with C++ (provides link.exe)"
    "Note:    Required on native Windows when headroom-tool-install is in the plan (Rust source build)."
  )
}

function Show-ToolHelp([string]$Tool) {
  Write-Host ""
  Write-Host "  $Tool is not installed or not on PATH."
  if ($ToolHelp.ContainsKey($Tool)) {
    $ToolHelp[$Tool] | ForEach-Object { Write-Host "  $_" }
  } else {
    Write-Host "  Install: add '$Tool' to your PATH, then re-run .\.agentic-config\install.ps1"
  }
}

function Show-HeadroomWindowsBuildHelp {
  if ($env:OS -ne "Windows_NT") { return }
  Write-Host ""
  Write-Host "  Headroom runtime on native Windows builds headroom-ai and ast-grep-cli from source"
  Write-Host "  (PyPI headroom-ai has Linux/macOS wheels only; ast-grep-cli Windows wheels may be"
  Write-Host "  quarantined by Defender - install.ps1 passes --no-binary-package ast-grep-cli)."
  Write-Host "  Install Rust (https://rustup.rs/) and Visual Studio Build Tools with"
  Write-Host "  Desktop development with C++ (provides link.exe), or use WSL/Linux instead."
  Write-Host "  Docs:    https://github.com/headroomlabs-ai/headroom"
  Write-Host ""
}

function Get-HeadroomToolInstallArgs($stepArgs) {
  # Windows: skip ast-grep-cli prebuilt wheel (Defender false positive on sg.exe during uv extract).
  return @(
    $stepArgs[0], $stepArgs[1], $stepArgs[2],
    "--no-binary-package", "ast-grep-cli",
    $stepArgs[3]
  )
}

function Get-HeadroomToolInstallCommand($step) {
  $package = $step.args[3]
  if ($env:OS -eq "Windows_NT") {
    return "uv tool install --force --no-binary-package ast-grep-cli '$package'"
  }
  return $step.command
}

function Test-MsvcLinkAvailable {
  if ($null -ne (Get-Command link.exe -ErrorAction SilentlyContinue)) { return $true }
  $vswhere = Join-Path ${env:ProgramFiles(x86)} "Microsoft Visual Studio\Installer\vswhere.exe"
  if (-not (Test-Path $vswhere)) { return $false }
  $installPath = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath 2>$null
  return [bool]$installPath
}

function Test-PlanIncludesHeadroomToolInstall($Plan) {
  return $null -ne ($Plan.steps | Where-Object { $_.id -eq "headroom-tool-install" } | Select-Object -First 1)
}

function Test-Have([string]$Bin) {
  return $null -ne (Get-Command $Bin -ErrorAction SilentlyContinue)
}

function Get-NodeVersion {
  $raw = node --version 2>$null
  if ($LASTEXITCODE -ne 0) { return $null }
  return $raw.TrimStart("v")
}

function Get-NodeMajorVersion {
  $version = Get-NodeVersion
  if ([string]::IsNullOrWhiteSpace($version)) { return $null }
  $majorText = ($version -split "\." | Select-Object -First 1)
  $major = 0
  if (-not [int]::TryParse($majorText, [ref]$major)) { return $null }
  return $major
}

function Test-NodeVersionSatisfiesMinimum {
  $major = Get-NodeMajorVersion
  if ($null -eq $major) { return $false }
  return $major -ge $MinNodeMajor
}

function Test-PlanRequiresNode($Plan) {
  return (Get-RequiredTools $Plan) -contains "node"
}

function Show-NodeVersionHelp([string]$Version) {
  Write-Host ""
  Write-Host "  Node.js $MinNodeMajor+ is required by this install plan."
  Write-Host "  Found:   $Version"
  Write-Host "  Docs:    https://nodejs.org/"
  Write-Host "  Install: winget install OpenJS.NodeJS.LTS"
  Write-Host "           # or: https://nodejs.org/en/download/"
}

function Ensure-GraphifyPath {
  $localBin = Join-Path $env:USERPROFILE ".local\bin"
  if (Test-Path $localBin) {
    $env:Path = "$localBin;$env:Path"
  }
}

function Ensure-HeadroomPath {
  $localBin = Join-Path $env:USERPROFILE ".local\bin"
  if (Test-Path $localBin) {
    $env:Path = "$localBin;$env:Path"
  }
}

function Test-PlanIncludesGraphify($Plan) {
  return $null -ne ($Plan.steps | Where-Object {
    $_.kind -eq "graphify-tool-install" -or $_.kind -eq "graphify-install"
  } | Select-Object -First 1)
}

# Env var list must match packages/agentic-config-core/lib/graphify-extraction-backend.mjs
# (GRAPHIFY_EXTRACTION_BACKEND_ENV_VARS); core.test.mjs asserts install scripts stay in sync.
function Test-GraphifyExtractionBackendEnv {
  $vars = @(
    "GEMINI_API_KEY", "GOOGLE_API_KEY", "ANTHROPIC_API_KEY", "OPENAI_API_KEY",
    "DEEPSEEK_API_KEY", "MOONSHOT_API_KEY", "OLLAMA_BASE_URL"
  )
  foreach ($key in $vars) {
    $val = [Environment]::GetEnvironmentVariable($key)
    if ($null -ne $val -and $val.Trim().Length -gt 0) {
      return $true
    }
  }
  return $false
}

function Show-GraphifyExtractionBackendWarning($Plan) {
  if (-not (Test-PlanIncludesGraphify $Plan)) { return }
  if (Test-GraphifyExtractionBackendEnv) { return }
  Write-Host ""
  Write-Host "[warn] No Graphify extraction backend detected (GEMINI_API_KEY, GOOGLE_API_KEY,"
  Write-Host "       ANTHROPIC_API_KEY, OPENAI_API_KEY, DEEPSEEK_API_KEY, MOONSHOT_API_KEY,"
  Write-Host "       or OLLAMA_BASE_URL)."
  Write-Host "       Semantic doc/image extraction needs a backend pip extra and env vars."
  Write-Host "       See .agentic-config/INSTALL.md and graphify.env.example."
  Write-Host "       Install still succeeded - AST-only indexing remains possible."
  Write-Host ""
}

function Get-RequiredTools($Plan) {
  $required = [System.Collections.Generic.HashSet[string]]::new()
  foreach ($step in $Plan.steps) {
    if ($step.optional) { continue }
    if ($step.kind -eq "pi-install" -and $SkipPi) { continue }
    if ($step.kind -eq "skills-add" -and $SkipSkills) { continue }
    if ($null -ne $step.requires) {
      foreach ($bin in $step.requires) {
        # graphify is installed by graphify-tool-install; headroom by headroom-tool-install.
        if ($bin -eq "graphify" -or $bin -eq "headroom") { continue }
        [void]$required.Add($bin)
      }
    }
  }
  return @($required)
}

function Invoke-EnvCheck($Plan) {
  Write-Host "Environment check"
  Write-Host "================="
  $missing = $false
  foreach ($tool in (Get-RequiredTools $Plan)) {
    if (Test-Have $tool) {
      Write-Host "[ok]   $tool"
    } else {
      Write-Host "[MISSING] $tool"
      Show-ToolHelp $tool
      $missing = $true
    }
  }
  if ($env:OS -eq "Windows_NT" -and (Test-PlanIncludesHeadroomToolInstall $Plan)) {
    if (Test-Have "cargo") {
      Write-Host "[ok]   cargo (Rust)"
    } else {
      Write-Host "[MISSING] cargo (Rust)"
      Show-ToolHelp "cargo"
      $missing = $true
    }
    if (Test-MsvcLinkAvailable) {
      Write-Host "[ok]   msvc (link.exe)"
    } else {
      Write-Host "[MISSING] msvc (link.exe)"
      Show-ToolHelp "msvc"
      $missing = $true
    }
  }
  if (-not $missing -and (Test-PlanRequiresNode $Plan)) {
    $nodeVersion = Get-NodeVersion
    if (-not (Test-NodeVersionSatisfiesMinimum)) {
      if ([string]::IsNullOrWhiteSpace($nodeVersion)) { $nodeVersion = "unknown" }
      Write-Host "[TOO OLD] node ($nodeVersion)"
      Show-NodeVersionHelp $nodeVersion
      $missing = $true
      Write-Host ""
    }
  }
  Write-Host ""
  if ($missing) {
    if ($env:OS -eq "Windows_NT" -and (Test-PlanIncludesHeadroomToolInstall $Plan)) {
      Show-HeadroomWindowsBuildHelp
    }
    Write-Host "One or more required tools are missing."
    Write-Host "Install the missing tools above, then re-run:"
    Write-Host "  .\.agentic-config\install.ps1"
    Write-Host ""
    Write-Host "To skip this check (not recommended): .\.agentic-config\install.ps1 -SkipEnvCheck"
    exit 1
  }
  Write-Host "All required tools are available."
  Write-Host ""
}

if (-not (Test-Path $PlanPath)) {
  Write-Error "install-plan.json not found in $ScriptDir"
}

$plan = Get-Content $PlanPath -Raw | ConvertFrom-Json

if (-not $SkipEnvCheck) {
  Invoke-EnvCheck $plan
}

$failed = $false
$upstreamWarnings = 0

foreach ($step in $plan.steps) {
  if ($step.kind -eq "pi-install" -and $SkipPi) {
    Write-Host "[skip] $($step.id) (-SkipPi)"
    continue
  }
  if ($step.kind -eq "skills-add" -and $SkipSkills) {
    Write-Host "[skip] $($step.id) (-SkipSkills)"
    continue
  }

  if ($step.kind -eq "graphify-install") {
    Ensure-GraphifyPath
  }

  if ($step.kind -eq "headroom-mcp" -or $step.kind -eq "headroom-tool") {
    Ensure-HeadroomPath
  }

  $missingReq = @()
  if ($null -ne $step.requires) {
    $missingReq = @(
      $step.requires | Where-Object {
        if ($DryRun -and ($_ -eq "graphify" -or $_ -eq "headroom")) { return $false }
        -not (Test-Have $_)
      }
    )
  }
  if ($missingReq.Count -gt 0) {
    if ($step.optional) {
      Write-Host "[skip] $($step.id) (missing prerequisite, optional)"
      continue
    }
    if (-not $Force) {
      foreach ($m in $missingReq) { Show-ToolHelp $m }
      Write-Host -ForegroundColor Red "[fail] $($step.id) requires: $($step.requires -join ', ')"
      exit 1
    }
    Write-Host "[warn] $($step.id) missing prerequisite, continuing (-Force)"
  }

  $runCommand = if ($step.id -eq "headroom-tool-install") { Get-HeadroomToolInstallCommand $step } else { $step.command }
  Write-Host "[run] $($step.id): $runCommand"
  if (-not $DryRun) {
    Push-Location $ProjectRoot
    try {
      $exitCode = 0
      if ($null -ne $step.exe) {
        $args = @()
        if ($null -ne $step.args) { $args = @($step.args) }
        if ($step.id -eq "headroom-tool-install" -and $env:OS -eq "Windows_NT") {
          $args = Get-HeadroomToolInstallArgs $args
        }
        & $step.exe @args
        $exitCode = $LASTEXITCODE
      } else {
        Invoke-Expression $step.command
        $exitCode = $LASTEXITCODE
      }
      if ($exitCode -ne 0) {
        if ($step.kind -eq "skills-add" -or $step.kind -eq "pi-install") {
          if ($Strict) {
            $failed = $true
            Write-Host -ForegroundColor Red "[fail] $($step.id) exited with code $exitCode"
            break
          }
          Write-Host "[warn] $($step.id): upstream install failed (exit $exitCode); skill may be missing upstream - refresh bundle or install manually"
          $upstreamWarnings++
          continue
        }
        if ($step.id -eq "headroom-tool-install") {
          Show-HeadroomWindowsBuildHelp
        }
        $failed = $true
        Write-Host -ForegroundColor Red "[fail] $($step.id) exited with code $exitCode"
        if (-not $step.optional) { break }
      }
    } catch {
      $failed = $true
      Write-Host -ForegroundColor Red "ERROR during step $($step.id): $_"
      if (-not $step.optional) { break }
    } finally {
      Pop-Location
    }
  }
}

if ($failed) { exit 1 }

# --- Install type recommendation ---
if ($DryRun) {
  $stepCount = @($plan.steps).Count
  Write-Host "Dry run complete ($stepCount steps)."
  Write-Host "Install type detected: $InstallType"
} else {
  Show-GraphifyExtractionBackendWarning $plan
  if ($upstreamWarnings -gt 0) {
    Write-Host "Installer finished with $upstreamWarnings warning(s)."
  } else {
    Write-Host "Installer finished successfully."
  }
  Write-Host ""
  switch ($InstallType) {
    "greenfield" {
      Write-Host "This appears to be a new repository with no prior ADC installation."
      Write-Host "Post-install review: .agentic-config/post-install-review-greenfield.md"
      Write-Host "Open the file, select all, and paste into your coding agent."
    }
    "integration" {
      Write-Host "This appears to be an existing repository without a prior ADC installation."
      Write-Host "Post-install review: .agentic-config/post-install-review-integration.md"
      Write-Host "Open the file, select all, and paste into your coding agent."
    }
    "update" {
      Write-Host "This appears to be an update to an existing ADC installation."
      Write-Host "Recommended post-install review: .agentic-config/post-install-review-update.md"
      Write-Host "Open the file, select all, and paste into your coding agent."
      Write-Host "The agent will compare the new bundle against the prior installation in git history."
    }
  }
  Write-Host ""
}
